feat: allow for current_dir failure
mehcode/config-rs pull request #247
Opened 2021-11-13 19:48 UTC by conradludgate

We have a potential use-case where a config is loaded while in a directory that doesn't exist (see https://github.com/ellie/atuin/issues/195). This PR makes the code a bit more accepting of whether the `env::current_dir` command fails, falling back on the filename as the `uri`.

2021-11-13 20:36 UTC, matthiasbeyer requested changes
Overall the diff looks good, except for the one thing I annotated.

CI fails because of an example, which should be fixed as well :smile:

2021-11-13 20:36 UTC, matthiasbeyer commented on src/file/source/file.rs
> -        let mut file = fs::File::open(filename)?;
This change does not belong to the other change you provided - please split it into a seperate commit!

2021-11-13 20:42 UTC, conradludgate commented
The CI failure looks like a network error, not a result of these changes

2021-11-14 09:35 UTC, conradludgate commented
The newest version of warp (`0.3.2`) included a new version of `tungsenite` which makes use of const generics. Pinning it to `0.3.1` fixes that

2021-11-20 08:59 UTC, matthiasbeyer commented
Sorry for taking so long, this week was really busy for me.

Did you test this change with your codebase? Because right above your change, `FileSourceFile::find_file()` is called, which calls `env::current_dir()?` right away, which would result in the same thing you're trying to fix here :laughing:

2021-11-20 09:20 UTC, conradludgate commented
Good point. I'll test it and see if it's all working. I'll then rebase after

2021-11-21 11:10 UTC, matthiasbeyer approved these changes

2021-11-21 11:10 UTC, merged