Unify deser impl
mehcode/config-rs pull request #338
Opened 2022-05-11 09:34 UTC by ijackson

As part of my efforts to try to make `#[deser(flatten)]` work correctly (#336) I did some refactoring.  Although the deser work is unfinished, I think these two commits are worth submitting separately.

2022-06-29 15:54 UTC, matthiasbeyer requested changes
Hi. Sorry for not getting back to this for such a long time... I had other things on my mind and then I was on vacation. :beach_umbrella: 

I hope you don't mind. :smile_cat: 

If you are not interested anymore in continuing work on this PR, I am happy to make the adaptions requested in my review myself!

2023-10-04 17:21 UTC, ijackson commented on tests/errors.rs
> +    expect_err(res);
I was expecting there might be more tests with errors, so wanted to provide a helper to check an error was expected.  I can inline this again if you prefer, which would probably make it a bit simpler looking.

2023-10-04 17:21 UTC, ijackson commented on src/de.rs
> -        // FIXME: This should *fail* if the value does not fit in the requets integer type
In the meantime those FIXMEs have gone and much of the code has been reorganised.  I'm going to fix #464 first and then maybe revisit this.

2023-10-05 11:52 UTC, matthiasbeyer commented on tests/errors.rs
> +    expect_err(res);
Yes do that please.

2023-10-23 18:14 UTC, ijackson commented
Closing in favour of #488

2023-10-23 18:14 UTC, closed without merging